/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pw.proz;

import org.junit.Test;
import static org.junit.Assert.assertNotNull;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App(); //App is tested
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
