/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pw.proz;

import org.junit.Test;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import pw.proz.window.GamePanel;

public class GamePanelTest {
    @Test public void testAppHasAGreeting() {
        GamePanel classUnderTest = new GamePanel(); //GamePanel is tested
        assertNotNull("GamePanel should create the player object", classUnderTest.getPlayer());
        assertTrue("GamePanel should initialise the game to the running state", classUnderTest.getRunning());
        assertNotNull("List of enemies in GamePanel should start as empty, but not null", classUnderTest.getEnemies());
        assertNotNull("List of bonuses in GamePanel should start as empty, but not null", classUnderTest.getBonuses());
    }
}
